### ISSUE TITLE
Part 2: Implement Multi-Stage Release System for claude-init Repository

### ISSUE THREAD

**Issue by garywu** [garywu/claude-init#3]
## Overview

Implement the multi-stage release system for the claude-init repository itself, making it a reliable dependency with predictable release channels.

## Scope

This issue covers implementing claude-init's own release management. The templates for other repositories are tracked in Issue #2.

#### 1. Create Release Branches
```bash
# Create beta branch from main
git checkout -b beta
git push -u origin beta

# Create stable branch from main  
git checkout -b stable
git push -u origin stable
```

#### 2. Configure Branch Protection
- **main**: Require PR reviews, status checks
- **beta**: Require status checks, no direct pushes
- **stable**: Require admin approval, no direct pushes

#### 1. Create `.github/workflows/release-beta.yml`
```yaml
name: Beta Release

on:
  schedule:
    # Every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:
    inputs:
      force_version:
        description: 'Force specific version'
        required: false

permissions:
  contents: write
  pull-requests: write

jobs:
  beta-release:
    runs-on: ubuntu-latest
    steps:
      # Implementation details...
```

#### 2. Create `.github/workflows/release-stable.yml`
```yaml
name: Stable Release

on:
  workflow_dispatch:
    inputs:
      beta_version:
        description: 'Beta version to promote'
        required: true

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  promote-stable:
    runs-on: ubuntu-latest
    steps:
      # Implementation details...
```

#### 3. Create `.github/workflows/sync-branches.yml`
- Keep branches in sync after releases
- Backport critical fixes
- Merge stable → beta → main after hotfixes

#### 1. Create `.github/release.yml`
```yaml
changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: 🚀 Features
      labels:
        - enhancement
        - feature
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - fix
    - title: 📚 Documentation
      labels:
        - documentation
    - title: 🔧 Maintenance
      labels:
        - chore
        - maintenance
```

#### 2. Update Repository Settings
- Enable "Automatically delete head branches"
- Set up webhook notifications
- Configure release announcements

#### 1. Initial Version Setup
- Tag current main as `v1.0.0`
- Create first beta: `v1.1.0-beta.1`
- Document version history

#### 2. Version Files
- Add VERSION file for easy reference
- Update in automated workflows
- Include in release artifacts

#### 1. Update README.md
```markdown
## Installation

### Stable (Recommended)
```bash
git submodule add -b stable https://github.com/garywu/claude-init.git
```

### Beta (Early Access)
```bash
git submodule add -b beta https://github.com/garywu/claude-init.git
```

### Development (Latest)
```bash
git submodule add https://github.com/garywu/claude-init.git
```
```

#### 2. Create RELEASES.md
- Document release process
- Include rollback procedures
- Add troubleshooting guide

### Phase 6: Testing & Validation

#### 1. Test Release Workflows
- Dry run beta release
- Test stable promotion
- Verify changelog generation
- Validate version bumping

#### 2. Integration Testing
- Test with dependent repositories
- Verify submodule updates
- Check notification systems

## Migration Plan

1. **Week 1**: Set up branches and protection rules
2. **Week 2**: Implement and test workflows
3. **Week 3**: First beta release (v1.1.0-beta.1)
4. **Week 4**: Documentation and refinement
5. **Month 2**: First stable release (v1.1.0)

## Success Metrics

- [ ] Weekly beta releases functioning
- [ ] Clean stable promotion process
- [ ] Zero breaking changes without major version bump
- [ ] Clear upgrade path documentation
- [ ] Positive feedback from users

## Risks & Mitigation

1. **Breaking existing dependencies**
   - Keep main branch as default initially
   - Provide migration guide
   - Announce changes in advance

2. **Workflow complexity**
   - Start simple, add features gradually
   - Comprehensive documentation
   - Test thoroughly before enabling

3. **Version conflicts**
   - Clear versioning strategy
   - Automated conflict detection
   - Rollback procedures ready

---

This implementation will establish claude-init as a professionally managed dependency with predictable release cycles and multiple stability channels.
